{{- $deploymentName := "n8n-main" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ $deploymentName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: {{ $deploymentName }}
    spec:
      restartPolicy: Always
      containers:
        - name: main
          image: n8nio/n8n:{{ .Values.n8n.imageTag }}
          imagePullPolicy: Always
          args: ["start"]
          envFrom:
          - configMapRef:
              name: n8n-configmap-env
          resources:
            limits:
              memory: {{ .Values.resources.memoryLimit }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $deploymentName }}
spec:
  type: ClusterIP
  selector:
    service: {{ $deploymentName }}
  ports:
    - port: 5678
